/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  MaterialCategory as PrismaMaterialCategory,
} from "@prisma/client";

export class MaterialCategoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.MaterialCategoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.materialCategory.count(args);
  }

  async materialCategories<T extends Prisma.MaterialCategoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialCategoryFindManyArgs>
  ): Promise<PrismaMaterialCategory[]> {
    return this.prisma.materialCategory.findMany<Prisma.MaterialCategoryFindManyArgs>(
      args
    );
  }
  async materialCategory<T extends Prisma.MaterialCategoryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialCategoryFindUniqueArgs>
  ): Promise<PrismaMaterialCategory | null> {
    return this.prisma.materialCategory.findUnique(args);
  }
  async createMaterialCategory<T extends Prisma.MaterialCategoryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialCategoryCreateArgs>
  ): Promise<PrismaMaterialCategory> {
    return this.prisma.materialCategory.create<T>(args);
  }
  async updateMaterialCategory<T extends Prisma.MaterialCategoryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialCategoryUpdateArgs>
  ): Promise<PrismaMaterialCategory> {
    return this.prisma.materialCategory.update<T>(args);
  }
  async deleteMaterialCategory<T extends Prisma.MaterialCategoryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.MaterialCategoryDeleteArgs>
  ): Promise<PrismaMaterialCategory> {
    return this.prisma.materialCategory.delete(args);
  }
}
